version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - flask_app

  sqlite_db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./data:/data
