version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile for your Flask app
    container_name: flask-app-docker
    ports:
      - "5000:5000"          # Flask app port
    volumes:
      - .:/app               # Mount the current directory inside the container for Flask
    environment:
      - FLASK_APP=app.py     # Set the FLASK_APP environment variable to your main Flask app file
      - FLASK_ENV=development # Set the environment to development
    command: flask run --host=0.0.0.0

  alfa-leetcode-api:
    build: .
    container_name: alfa-leetcode-api-docker
    ports:
      - '3000:3000'
    restart: always
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
